import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
  Package, ChevronLeft, Loader2, AlertCircle, CheckCircle2,
  Tag, Hash, Building2, MapPin, DollarSign, Calendar, Link2,
} from 'lucide-react';
import { createAsset, getCategories, getDepartments } from '../../api/assetApi';
import { useCurrentUser } from '../../hooks/useCurrentUser';

// ─── Exact condition options (free-text per schema, but guided choices) ───────
const CONDITION_OPTIONS = ['Good', 'Fair', 'Poor'];

// ─── Validation ───────────────────────────────────────────────────────────────
function validateForm(f) {
  const errors = {};
  if (!f.name.trim())       errors.name = 'Asset name is required.';
  if (!f.categoryId)        errors.categoryId = 'Category is required.';
  if (!f.condition)         errors.condition = 'Condition is required.';
  if (f.acquisitionCost && isNaN(Number(f.acquisitionCost))) {
    errors.acquisitionCost = 'Cost must be a number.';
  }
  return errors;
}

// ─── Field helpers ────────────────────────────────────────────────────────────
function FieldError({ id, msg }) {
  if (!msg) return null;
  return <p id={id} className="mt-1 text-xs text-red-600">{msg}</p>;
}

function Label({ htmlFor, children, required }) {
  return (
    <label htmlFor={htmlFor} className="block text-sm font-medium text-slate-700 mb-1">
      {children}{required && <span className="text-red-500 ml-0.5">*</span>}
    </label>
  );
}

function inputCls(hasError) {
  return [
    'block w-full rounded-md border px-3 py-2 text-sm text-slate-900 placeholder-slate-400 outline-none',
    'focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-colors duration-150',
    hasError
      ? 'border-red-400 bg-red-50'
      : 'border-slate-300 bg-white hover:border-slate-400',
  ].join(' ');
}

function iconInputCls(hasError) {
  return inputCls(hasError) + ' pl-9';
}

// ─── Component ────────────────────────────────────────────────────────────────
/**
 * AssetRegistrationForm — Screen 4 (Asset Core, Member 2)
 *
 * POST /api/v1/assets  (Asset Manager role only)
 * Asset Tag is auto-generated by the backend — user does NOT enter it.
 * Photo field = photoUrl text input (no cloud upload per ACCEPTANCE_CRITERIA.md).
 */
export default function AssetRegistrationForm() {
  const navigate = useNavigate();
  const { user } = useCurrentUser();

  // ── Dropdown data ────────────────────────────────────────────────────────────
  const [categories, setCategories] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [loadingDropdowns, setLoadingDropdowns] = useState(true);

  // ── Form state ───────────────────────────────────────────────────────────────
  const EMPTY = {
    name: '',
    serialNumber: '',
    categoryId: '',
    departmentId: '',
    isBookable: false,
    acquisitionDate: '',
    acquisitionCost: '',
    condition: '',
    location: '',
    photoUrl: '',
  };
  const [fields, setFields] = useState(EMPTY);
  const [fieldErrors, setFieldErrors] = useState({});
  const [serverError, setServerError] = useState('');
  const [successTag, setSuccessTag] = useState(''); // asset tag returned on success
  const [isSubmitting, setIsSubmitting] = useState(false);

  // ── Load dropdowns ───────────────────────────────────────────────────────────
  useEffect(() => {
    async function load() {
      setLoadingDropdowns(true);
      try {
        const [catRes, deptRes] = await Promise.all([
          getCategories(),
          getDepartments({ status: 'ACTIVE' }),
        ]);
        // standard envelope: { success, data } OR plain array
        const cats = catRes.data?.data ?? catRes.data ?? [];
        const depts = deptRes.data?.data ?? deptRes.data ?? [];
        setCategories(Array.isArray(cats) ? cats : []);
        setDepartments(Array.isArray(depts) ? depts : []);
      } catch (err) {
        console.error('Failed to load dropdowns:', err);
      } finally {
        setLoadingDropdowns(false);
      }
    }
    load();
  }, []);

  // ── Handlers ─────────────────────────────────────────────────────────────────
  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    const val = type === 'checkbox' ? checked : value;
    setFields((prev) => ({ ...prev, [name]: val }));
    if (fieldErrors[name]) setFieldErrors((prev) => ({ ...prev, [name]: '' }));
    if (serverError) setServerError('');
    if (successTag) setSuccessTag('');
  }

  async function handleSubmit(e) {
    e.preventDefault();
    setServerError('');
    setSuccessTag('');

    const errors = validateForm(fields);
    if (Object.keys(errors).length) { setFieldErrors(errors); return; }

    setIsSubmitting(true);
    try {
      // Build payload — omit assetTag (auto-generated by backend)
      const payload = {
        name: fields.name.trim(),
        categoryId: fields.categoryId,
        isBookable: fields.isBookable,
        condition: fields.condition,
        ...(fields.serialNumber  && { serialNumber:    fields.serialNumber.trim() }),
        ...(fields.departmentId  && { departmentId:    fields.departmentId }),
        ...(fields.acquisitionDate && { acquisitionDate: fields.acquisitionDate }),
        ...(fields.acquisitionCost && { acquisitionCost: Number(fields.acquisitionCost) }),
        ...(fields.location      && { location:        fields.location.trim() }),
        ...(fields.photoUrl      && { photoUrl:        fields.photoUrl.trim() }),
      };

      const res = await createAsset(payload);
      // success envelope: { success: true, data: { assetTag, ... } }
      const created = res.data?.data ?? res.data;
      setSuccessTag(created?.assetTag ?? 'AF-????');
      setFields(EMPTY);
    } catch (err) {
      const msg =
        err?.response?.data?.error?.message ||
        err?.response?.data?.message ||
        null;
      if (!err?.response) {
        setServerError('Cannot reach the server. Check your connection.');
      } else {
        setServerError(msg || 'Failed to register asset. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  }

  // ── Role gate — Asset Manager only ──────────────────────────────────────────
  if (user && user.role !== 'ASSET_MANAGER' && user.role !== 'ADMIN') {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-8">
        <div className="text-center max-w-sm">
          <AlertCircle className="h-10 w-10 text-red-400 mx-auto mb-3" />
          <h2 className="text-lg font-semibold text-slate-800">Access Restricted</h2>
          <p className="text-sm text-slate-500 mt-1">
            Only Asset Managers can register assets.
          </p>
          <Link to="/assets" className="mt-4 inline-block text-sm text-indigo-600 hover:underline">
            ← Back to Asset Directory
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* ── Page header ─────────────────────────────────────────────────────── */}
      <div className="bg-white border-b border-slate-200 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center gap-3">
          <button
            type="button"
            onClick={() => navigate('/assets')}
            className="text-slate-500 hover:text-slate-700 focus-visible:ring-2 focus-visible:ring-indigo-500 rounded transition-colors"
            aria-label="Back to directory"
          >
            <ChevronLeft className="h-5 w-5" />
          </button>
          <Package className="h-5 w-5 text-indigo-600" aria-hidden="true" />
          <div>
            <h1 className="text-lg font-semibold text-slate-900">Register New Asset</h1>
            <p className="text-xs text-slate-500">Asset Tag will be auto-generated by the system.</p>
          </div>
        </div>
      </div>

      {/* ── Form ────────────────────────────────────────────────────────────── */}
      <div className="max-w-3xl mx-auto px-6 py-8">
        {/* Success banner */}
        {successTag && (
          <div className="mb-6 flex items-start gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3">
            <CheckCircle2 className="h-5 w-5 text-emerald-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-emerald-800">
                Asset registered — Tag: <span className="font-mono font-bold">{successTag}</span>
              </p>
              <p className="text-xs text-emerald-700 mt-0.5">
                Form cleared. You can register another asset or{' '}
                <Link to="/assets" className="underline">view the directory.</Link>
              </p>
            </div>
          </div>
        )}

        {/* Server error */}
        {serverError && (
          <div
            role="alert"
            aria-live="polite"
            className="mb-6 flex items-start gap-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
          >
            <AlertCircle className="h-4 w-4 mt-0.5 flex-shrink-0" />
            <span>{serverError}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate aria-label="Asset registration form">
          <div className="bg-white border border-slate-200 rounded-lg divide-y divide-slate-100">

            {/* ── Section 1: Core identity ─────────────────────────────────── */}
            <div className="px-6 py-5">
              <h2 className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-4">
                Asset Identity
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                {/* Asset Tag — read-only info */}
                <div className="sm:col-span-2">
                  <div className="flex items-center gap-2 rounded-md border border-dashed border-slate-300 bg-slate-50 px-3 py-2.5 text-sm text-slate-500">
                    <Tag className="h-4 w-4 text-slate-400 flex-shrink-0" />
                    <span>
                      <span className="font-medium text-slate-600">Asset Tag</span> — automatically assigned by the system (e.g.{' '}
                      <span className="font-mono">AF-0042</span>)
                    </span>
                  </div>
                </div>

                {/* Name */}
                <div className="sm:col-span-2">
                  <Label htmlFor="name" required>Asset Name</Label>
                  <div className="relative">
                    <input
                      id="name"
                      name="name"
                      type="text"
                      value={fields.name}
                      onChange={handleChange}
                      placeholder="e.g. Dell XPS 15 Laptop"
                      aria-invalid={Boolean(fieldErrors.name)}
                      aria-describedby={fieldErrors.name ? 'name-err' : undefined}
                      className={iconInputCls(fieldErrors.name)}
                    />
                    <Package className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                  <FieldError id="name-err" msg={fieldErrors.name} />
                </div>

                {/* Serial Number */}
                <div>
                  <Label htmlFor="serialNumber">Serial Number</Label>
                  <div className="relative">
                    <input
                      id="serialNumber"
                      name="serialNumber"
                      type="text"
                      value={fields.serialNumber}
                      onChange={handleChange}
                      placeholder="e.g. SN-1234567890"
                      className={iconInputCls(false)}
                    />
                    <Hash className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                </div>

                {/* Category */}
                <div>
                  <Label htmlFor="categoryId" required>Category</Label>
                  <select
                    id="categoryId"
                    name="categoryId"
                    value={fields.categoryId}
                    onChange={handleChange}
                    disabled={loadingDropdowns}
                    aria-invalid={Boolean(fieldErrors.categoryId)}
                    aria-describedby={fieldErrors.categoryId ? 'cat-err' : undefined}
                    className={inputCls(fieldErrors.categoryId) + ' appearance-none'}
                  >
                    <option value="">
                      {loadingDropdowns ? 'Loading…' : 'Select category'}
                    </option>
                    {categories.map((c) => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                  <FieldError id="cat-err" msg={fieldErrors.categoryId} />
                </div>
              </div>
            </div>

            {/* ── Section 2: Assignment ─────────────────────────────────────── */}
            <div className="px-6 py-5">
              <h2 className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-4">
                Assignment & Location
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                {/* Department (optional) */}
                <div>
                  <Label htmlFor="departmentId">Department <span className="text-xs font-normal text-slate-400">(optional)</span></Label>
                  <div className="relative">
                    <select
                      id="departmentId"
                      name="departmentId"
                      value={fields.departmentId}
                      onChange={handleChange}
                      disabled={loadingDropdowns}
                      className={inputCls(false) + ' appearance-none pl-9'}
                    >
                      <option value="">
                        {loadingDropdowns ? 'Loading…' : 'No department'}
                      </option>
                      {departments.map((d) => (
                        <option key={d.id} value={d.id}>{d.name}</option>
                      ))}
                    </select>
                    <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                </div>

                {/* Location */}
                <div>
                  <Label htmlFor="location">Location</Label>
                  <div className="relative">
                    <input
                      id="location"
                      name="location"
                      type="text"
                      value={fields.location}
                      onChange={handleChange}
                      placeholder="e.g. HQ Floor 2, Warehouse"
                      className={iconInputCls(false)}
                    />
                    <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                </div>
              </div>
            </div>

            {/* ── Section 3: Acquisition details ────────────────────────────── */}
            <div className="px-6 py-5">
              <h2 className="text-sm font-semibold text-slate-700 uppercase tracking-wide mb-4">
                Acquisition Details
              </h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

                {/* Acquisition Date */}
                <div>
                  <Label htmlFor="acquisitionDate">Acquisition Date</Label>
                  <div className="relative">
                    <input
                      id="acquisitionDate"
                      name="acquisitionDate"
                      type="date"
                      value={fields.acquisitionDate}
                      onChange={handleChange}
                      className={iconInputCls(false)}
                    />
                    <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                </div>

                {/* Acquisition Cost */}
                <div>
                  <Label htmlFor="acquisitionCost">Acquisition Cost (₹)</Label>
                  <div className="relative">
                    <input
                      id="acquisitionCost"
                      name="acquisitionCost"
                      type="number"
                      min="0"
                      step="0.01"
                      value={fields.acquisitionCost}
                      onChange={handleChange}
                      placeholder="0.00"
                      aria-invalid={Boolean(fieldErrors.acquisitionCost)}
                      aria-describedby={fieldErrors.acquisitionCost ? 'cost-err' : undefined}
                      className={iconInputCls(fieldErrors.acquisitionCost)}
                    />
                    <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                  <FieldError id="cost-err" msg={fieldErrors.acquisitionCost} />
                </div>

                {/* Condition */}
                <div>
                  <Label htmlFor="condition" required>Condition</Label>
                  <select
                    id="condition"
                    name="condition"
                    value={fields.condition}
                    onChange={handleChange}
                    aria-invalid={Boolean(fieldErrors.condition)}
                    aria-describedby={fieldErrors.condition ? 'cond-err' : undefined}
                    className={inputCls(fieldErrors.condition) + ' appearance-none'}
                  >
                    <option value="">Select condition</option>
                    {CONDITION_OPTIONS.map((c) => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                  <FieldError id="cond-err" msg={fieldErrors.condition} />
                </div>

                {/* Photo URL — no cloud upload per ACCEPTANCE_CRITERIA.md */}
                <div>
                  <Label htmlFor="photoUrl">Photo URL <span className="text-xs font-normal text-slate-400">(optional, paste link)</span></Label>
                  <div className="relative">
                    <input
                      id="photoUrl"
                      name="photoUrl"
                      type="url"
                      value={fields.photoUrl}
                      onChange={handleChange}
                      placeholder="https://…"
                      className={iconInputCls(false)}
                    />
                    <Link2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400 pointer-events-none" />
                  </div>
                </div>
              </div>
            </div>

            {/* ── Section 4: Flags ─────────────────────────────────────────── */}
            <div className="px-6 py-5">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-slate-700">Bookable Resource</p>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Enable if this asset can be reserved via the Booking calendar (e.g. conference room, projector).
                  </p>
                </div>
                <label className="relative inline-flex items-center cursor-pointer" htmlFor="isBookable">
                  <input
                    id="isBookable"
                    name="isBookable"
                    type="checkbox"
                    checked={fields.isBookable}
                    onChange={handleChange}
                    className="sr-only peer"
                  />
                  <div className="w-10 h-5 bg-slate-200 peer-focus-visible:ring-2 peer-focus-visible:ring-indigo-500 rounded-full peer peer-checked:bg-indigo-600 transition-colors after:content-[''] after:absolute after:top-0.5 after:left-0.5 after:bg-white after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:after:translate-x-5" />
                </label>
              </div>
            </div>

            {/* ── Actions ──────────────────────────────────────────────────── */}
            <div className="px-6 py-4 flex items-center justify-end gap-3">
              <button
                type="button"
                onClick={() => navigate('/assets')}
                className="px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-300 rounded-md hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-indigo-500 transition-colors"
              >
                Cancel
              </button>
              <button
                id="register-asset-btn"
                type="submit"
                disabled={isSubmitting}
                className="inline-flex items-center gap-2 px-5 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 rounded-md focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
                aria-busy={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Registering…
                  </>
                ) : (
                  <>
                    <Package className="h-4 w-4" />
                    Register Asset
                  </>
                )}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
