import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import {
  Package, ChevronLeft, Loader2, AlertCircle, CheckCircle2,
  Tag, Hash, Building2, MapPin, DollarSign, Calendar, Link2,
} from 'lucide-react';
import { createAsset, getCategories, getDepartments } from '../../api/assetApi';
import useAuth from '../../hooks/useAuth';
import { useToast } from '../../components/Toast/ToastProvider';

// ─── Exact condition options (free-text per schema, but guided choices) ───────
const CONDITION_OPTIONS = ['Good', 'Fair', 'Poor'];

// ─── Validation ───────────────────────────────────────────────────────────────
function validateForm(f) {
  const errors = {};
  if (!f.name.trim())       errors.name = 'Asset name is required.';
  if (!f.categoryId)        errors.categoryId = 'Category is required.';
  if (!f.condition)         errors.condition = 'Condition is required.';
  if (f.acquisitionCost && isNaN(Number(f.acquisitionCost))) {
    errors.acquisitionCost = 'Cost must be a number.';
  }
  return errors;
}

// ─── Field helpers ────────────────────────────────────────────────────────────
function FieldError({ id, msg }) {
  if (!msg) return null;
  return <p id={id} style={{ marginTop: 4, fontSize: 12, color: 'var(--color-semantic-error)' }}>{msg}</p>;
}

function Label({ htmlFor, children, required }) {
  return (
    <label htmlFor={htmlFor} className="field-label" style={{ display: 'block', marginBottom: 4 }}>
      {children}{required && <span style={{ color: 'var(--color-semantic-error)', marginLeft: 2 }}>*</span>}
    </label>
  );
}

function inputCls(hasError) {
  return hasError ? 'input-field !border-semantic-error !ring-semantic-error/20' : 'input-field';
}

function iconInputCls(hasError) {
  return inputCls(hasError) + ' pl-9';
}

// ─── Component ────────────────────────────────────────────────────────────────
/**
 * AssetRegistrationForm — Screen 4 (Asset Core, Member 2)
 *
 * POST /api/v1/assets  (Asset Manager role only)
 * Asset Tag is auto-generated by the backend — user does NOT enter it.
 * Photo field = photoUrl text input (no cloud upload per ACCEPTANCE_CRITERIA.md).
 */
export default function AssetRegistrationForm() {
  const navigate = useNavigate();
  const { currentUser: user } = useAuth();
  const { success } = useToast();

  // ── Dropdown data ────────────────────────────────────────────────────────────
  const [categories, setCategories] = useState([]);
  const [departments, setDepartments] = useState([]);
  const [loadingDropdowns, setLoadingDropdowns] = useState(true);

  // ── Form state ───────────────────────────────────────────────────────────────
  const EMPTY = {
    name: '',
    serialNumber: '',
    categoryId: '',
    departmentId: '',
    isBookable: false,
    acquisitionDate: '',
    acquisitionCost: '',
    condition: '',
    location: '',
    photoUrl: '',
  };
  const [fields, setFields] = useState(EMPTY);
  const [fieldErrors, setFieldErrors] = useState({});
  const [serverError, setServerError] = useState('');
  const [successTag, setSuccessTag] = useState(''); // asset tag returned on success
  const [isSubmitting, setIsSubmitting] = useState(false);

  // ── Load dropdowns ───────────────────────────────────────────────────────────
  useEffect(() => {
    async function load() {
      setLoadingDropdowns(true);
      try {
        const [catRes, deptRes] = await Promise.all([
          getCategories(),
          getDepartments({ status: 'ACTIVE' }),
        ]);
        // standard envelope: { success, data } OR plain array
        const cats = catRes.data?.data ?? catRes.data ?? [];
        const depts = deptRes.data?.data ?? deptRes.data ?? [];
        setCategories(Array.isArray(cats) ? cats : []);
        setDepartments(Array.isArray(depts) ? depts : []);
      } catch (err) {
        console.error('Failed to load dropdowns:', err);
      } finally {
        setLoadingDropdowns(false);
      }
    }
    load();
  }, []);

  // ── Handlers ─────────────────────────────────────────────────────────────────
  function handleChange(e) {
    const { name, value, type, checked } = e.target;
    const val = type === 'checkbox' ? checked : value;
    setFields((prev) => ({ ...prev, [name]: val }));
    if (fieldErrors[name]) setFieldErrors((prev) => ({ ...prev, [name]: '' }));
    if (serverError) setServerError('');
    if (successTag) setSuccessTag('');
  }

  async function handleSubmit(e) {
    e.preventDefault();
    setServerError('');
    setSuccessTag('');

    const errors = validateForm(fields);
    if (Object.keys(errors).length) { setFieldErrors(errors); return; }

    setIsSubmitting(true);
    try {
      // Build payload — omit assetTag (auto-generated by backend)
      const payload = {
        name: fields.name.trim(),
        categoryId: fields.categoryId,
        isBookable: fields.isBookable,
        condition: fields.condition,
        ...(fields.serialNumber  && { serialNumber:    fields.serialNumber.trim() }),
        ...(fields.departmentId  && { departmentId:    fields.departmentId }),
        ...(fields.acquisitionDate && { acquisitionDate: fields.acquisitionDate }),
        ...(fields.acquisitionCost && { acquisitionCost: Number(fields.acquisitionCost) }),
        ...(fields.location      && { location:        fields.location.trim() }),
        ...(fields.photoUrl      && { photoUrl:        fields.photoUrl.trim() }),
      };

      const res = await createAsset(payload);
      // success envelope: { success: true, data: { assetTag, ... } }
      const created = res.data?.data ?? res.data;
      const tag = created?.assetTag ?? 'AF-????';
      setSuccessTag(tag);
      setFields(EMPTY);
      success(`${fields.name || 'Asset'} registered`, { title: `Asset tag ${tag}` });
    } catch (err) {
      const msg =
        err?.response?.data?.error?.message ||
        err?.response?.data?.message ||
        null;
      if (!err?.response) {
        setServerError('Cannot reach the server. Check your connection.');
      } else {
        setServerError(msg || 'Failed to register asset. Please try again.');
      }
    } finally {
      setIsSubmitting(false);
    }
  }

  // ── Role gate — Asset Manager only ──────────────────────────────────────────
  if (user && user.role !== 'ASSET_MANAGER' && user.role !== 'ADMIN') {
    return (
      <div style={{ minHeight: '100vh', backgroundColor: 'var(--color-canvas)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 32 }}>
        <div style={{ textAlign: 'center', maxWidth: 384 }}>
          <AlertCircle size={40} color='var(--color-semantic-error)' style={{ margin: '0 auto 12px' }} />
          <h2 style={{ fontSize: 18, fontWeight: 600, color: 'var(--color-ink)', margin: '0 0 4px' }}>Access Restricted</h2>
          <p style={{ fontSize: 14, color: 'var(--color-ink-subtle)', margin: 0 }}>
            Only Asset Managers can register assets.
          </p>
          <Link to="/assets" style={{ display: 'inline-block', marginTop: 16, fontSize: 14, color: 'var(--color-primary)', textDecoration: 'none' }}>
            ← Back to Asset Directory
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div style={{ minHeight: '100vh', backgroundColor: 'var(--color-canvas)', color: 'var(--color-ink-muted)' }}>
      {/* ── Page header ─────────────────────────────────────────────────────── */}
      <div style={{ backgroundColor: 'var(--color-surface-1)', borderBottom: '1px solid var(--color-hairline)', padding: '16px 24px' }}>
        <div style={{ maxWidth: 768, margin: '0 auto', display: 'flex', alignItems: 'center', gap: 12 }}>
          <button
            type="button"
            onClick={() => navigate('/assets')}
            style={{ color: 'var(--color-ink-subtle)', background: 'none', border: 'none', cursor: 'pointer', padding: 4 }}
            aria-label="Back to directory"
          >
            <ChevronLeft size={20} />
          </button>
          <Package size={20} color='var(--color-primary)' aria-hidden="true" />
          <div>
            <h1 style={{ fontSize: 18, fontWeight: 600, color: 'var(--color-ink)', margin: 0 }}>Register New Asset</h1>
            <p style={{ fontSize: 12, color: 'var(--color-ink-subtle)', margin: '2px 0 0' }}>Asset Tag will be auto-generated by the system.</p>
          </div>
        </div>
      </div>

      {/* ── Form ────────────────────────────────────────────────────────────── */}
      <div style={{ maxWidth: 768, margin: '0 auto', padding: '32px 24px' }}>
        {/* Success banner */}
        {successTag && (
          <div style={{ marginBottom: 24, display: 'flex', alignItems: 'flex-start', gap: 12, borderRadius: 8, border: '1px solid var(--color-status-available-bg)', backgroundColor: 'var(--color-status-available-bg)', padding: '12px 16px' }}>
            <CheckCircle2 size={20} color='var(--color-status-available)' style={{ marginTop: 2, flexShrink: 0 }} />
            <div>
              <p style={{ fontSize: 14, fontWeight: 500, color: 'var(--color-status-available)', margin: 0 }}>
                Asset registered — Tag: <span style={{ fontFamily: 'var(--font-mono)', fontWeight: 600 }}>{successTag}</span>
              </p>
              <p style={{ fontSize: 12, color: 'var(--color-status-available)', margin: '2px 0 0' }}>
                Form cleared. You can register another asset or{' '}
                <Link to="/assets" style={{ textDecoration: 'underline', color: 'inherit' }}>view the directory.</Link>
              </p>
            </div>
          </div>
        )}

        {/* Server error */}
        {serverError && (
          <div
            role="alert"
            aria-live="polite"
            style={{ marginBottom: 24, display: 'flex', alignItems: 'flex-start', gap: 12, borderRadius: 8, border: '1px solid var(--color-semantic-error)', backgroundColor: 'var(--color-semantic-error-bg)', padding: '12px 16px', fontSize: 14, color: 'var(--color-semantic-error)' }}
          >
            <AlertCircle size={16} style={{ marginTop: 2, flexShrink: 0 }} />
            <span>{serverError}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate aria-label="Asset registration form">
          <div style={{ backgroundColor: 'var(--color-surface-1)', border: '1px solid var(--color-hairline)', borderRadius: 8 }}>

            {/* ── Section 1: Core identity ─────────────────────────────────── */}
            <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-hairline)' }}>
              <h2 style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-ink-subtle)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 16px' }}>
                Asset Identity
              </h2>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>

                {/* Asset Tag — read-only info */}
                <div style={{ gridColumn: 'span 2' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, borderRadius: 6, border: '1px dashed var(--color-hairline-strong)', backgroundColor: 'var(--color-surface-2)', padding: '10px 12px', fontSize: 13, color: 'var(--color-ink-subtle)' }}>
                    <Tag size={16} color='var(--color-ink-subtle)' style={{ flexShrink: 0 }} />
                    <span>
                      <span style={{ fontWeight: 500, color: 'var(--color-ink-muted)' }}>Asset Tag</span> — automatically assigned by the system (e.g.{' '}
                      <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--color-ink)' }}>AF-0042</span>)
                    </span>
                  </div>
                </div>

                {/* Name */}
                <div style={{ gridColumn: 'span 2' }}>
                  <Label htmlFor="name" required>Asset Name</Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="name"
                      name="name"
                      type="text"
                      value={fields.name}
                      onChange={handleChange}
                      placeholder="e.g. Dell XPS 15 Laptop"
                      aria-invalid={Boolean(fieldErrors.name)}
                      aria-describedby={fieldErrors.name ? 'name-err' : undefined}
                      className={iconInputCls(fieldErrors.name)}
                    />
                    <Package size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                  <FieldError id="name-err" msg={fieldErrors.name} />
                </div>

                {/* Serial Number */}
                <div>
                  <Label htmlFor="serialNumber">Serial Number</Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="serialNumber"
                      name="serialNumber"
                      type="text"
                      value={fields.serialNumber}
                      onChange={handleChange}
                      placeholder="e.g. SN-1234567890"
                      className={iconInputCls(false)}
                    />
                    <Hash size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                </div>

                {/* Category */}
                <div>
                  <Label htmlFor="categoryId" required>Category</Label>
                  <select
                    id="categoryId"
                    name="categoryId"
                    value={fields.categoryId}
                    onChange={handleChange}
                    disabled={loadingDropdowns}
                    aria-invalid={Boolean(fieldErrors.categoryId)}
                    aria-describedby={fieldErrors.categoryId ? 'cat-err' : undefined}
                    className={inputCls(fieldErrors.categoryId) + ' appearance-none'}
                  >
                    <option value="">
                      {loadingDropdowns ? 'Loading…' : 'Select category'}
                    </option>
                    {categories.map((c) => (
                      <option key={c.id} value={c.id}>{c.name}</option>
                    ))}
                  </select>
                  <FieldError id="cat-err" msg={fieldErrors.categoryId} />
                </div>
              </div>
            </div>

            {/* ── Section 2: Assignment ─────────────────────────────────────── */}
            <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-hairline)' }}>
              <h2 style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-ink-subtle)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 16px' }}>
                Assignment & Location
              </h2>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>

                {/* Department (optional) */}
                <div>
                  <Label htmlFor="departmentId">Department <span style={{ fontSize: 11, fontWeight: 400, color: 'var(--color-ink-subtle)' }}>(optional)</span></Label>
                  <div style={{ position: 'relative' }}>
                    <select
                      id="departmentId"
                      name="departmentId"
                      value={fields.departmentId}
                      onChange={handleChange}
                      disabled={loadingDropdowns}
                      className={inputCls(false) + ' appearance-none pl-9'}
                    >
                      <option value="">
                        {loadingDropdowns ? 'Loading…' : 'No department'}
                      </option>
                      {departments.map((d) => (
                        <option key={d.id} value={d.id}>{d.name}</option>
                      ))}
                    </select>
                    <Building2 size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                </div>

                {/* Location */}
                <div>
                  <Label htmlFor="location">Location</Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="location"
                      name="location"
                      type="text"
                      value={fields.location}
                      onChange={handleChange}
                      placeholder="e.g. HQ Floor 2, Warehouse"
                      className={iconInputCls(false)}
                    />
                    <MapPin size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                </div>
              </div>
            </div>

            {/* ── Section 3: Acquisition details ────────────────────────────── */}
            <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-hairline)' }}>
              <h2 style={{ fontSize: 11, fontWeight: 600, color: 'var(--color-ink-subtle)', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 16px' }}>
                Acquisition Details
              </h2>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>

                {/* Acquisition Date */}
                <div>
                  <Label htmlFor="acquisitionDate">Acquisition Date</Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="acquisitionDate"
                      name="acquisitionDate"
                      type="date"
                      value={fields.acquisitionDate}
                      onChange={handleChange}
                      className={iconInputCls(false)}
                    />
                    <Calendar size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                </div>

                {/* Acquisition Cost */}
                <div>
                  <Label htmlFor="acquisitionCost">Acquisition Cost (₹)</Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="acquisitionCost"
                      name="acquisitionCost"
                      type="number"
                      min="0"
                      step="0.01"
                      value={fields.acquisitionCost}
                      onChange={handleChange}
                      placeholder="0.00"
                      aria-invalid={Boolean(fieldErrors.acquisitionCost)}
                      aria-describedby={fieldErrors.acquisitionCost ? 'cost-err' : undefined}
                      className={iconInputCls(fieldErrors.acquisitionCost)}
                    />
                    <DollarSign size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                  <FieldError id="cost-err" msg={fieldErrors.acquisitionCost} />
                </div>

                {/* Condition */}
                <div>
                  <Label htmlFor="condition" required>Condition</Label>
                  <select
                    id="condition"
                    name="condition"
                    value={fields.condition}
                    onChange={handleChange}
                    aria-invalid={Boolean(fieldErrors.condition)}
                    aria-describedby={fieldErrors.condition ? 'cond-err' : undefined}
                    className={inputCls(fieldErrors.condition) + ' appearance-none'}
                  >
                    <option value="">Select condition</option>
                    {CONDITION_OPTIONS.map((c) => (
                      <option key={c} value={c}>{c}</option>
                    ))}
                  </select>
                  <FieldError id="cond-err" msg={fieldErrors.condition} />
                </div>

                {/* Photo URL — no cloud upload per ACCEPTANCE_CRITERIA.md */}
                <div>
                  <Label htmlFor="photoUrl">Photo URL <span style={{ fontSize: 11, fontWeight: 400, color: 'var(--color-ink-subtle)' }}>(optional, paste link)</span></Label>
                  <div style={{ position: 'relative' }}>
                    <input
                      id="photoUrl"
                      name="photoUrl"
                      type="url"
                      value={fields.photoUrl}
                      onChange={handleChange}
                      placeholder="https://…"
                      className={iconInputCls(false)}
                    />
                    <Link2 size={16} color='var(--color-ink-subtle)' style={{ position: 'absolute', left: 12, top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none' }} />
                  </div>
                </div>
              </div>
            </div>

            {/* ── Section 4: Flags ─────────────────────────────────────────── */}
            <div style={{ padding: '20px 24px', borderBottom: '1px solid var(--color-hairline)' }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div>
                  <p style={{ fontSize: 14, fontWeight: 500, color: 'var(--color-ink)', margin: 0 }}>Bookable Resource</p>
                  <p style={{ fontSize: 12, color: 'var(--color-ink-subtle)', margin: '2px 0 0' }}>
                    Enable if this asset can be reserved via the Booking calendar (e.g. conference room, projector).
                  </p>
                </div>
                <label style={{ position: 'relative', display: 'inline-flex', alignItems: 'center', cursor: 'pointer' }} htmlFor="isBookable">
                  <input
                    id="isBookable"
                    name="isBookable"
                    type="checkbox"
                    checked={fields.isBookable}
                    onChange={handleChange}
                    className="sr-only peer"
                  />
                  <div style={{ width: 40, height: 20, backgroundColor: fields.isBookable ? 'var(--color-primary)' : 'var(--color-hairline-strong)', borderRadius: 9999, transition: 'background-color 0.2s ease', position: 'relative' }}>
                    <div style={{ position: 'absolute', top: 2, left: fields.isBookable ? 22 : 2, width: 16, height: 16, backgroundColor: 'var(--color-on-primary)', borderRadius: '50%', transition: 'left 0.2s ease' }} />
                  </div>
                </label>
              </div>
            </div>

            {/* ── Actions ──────────────────────────────────────────────────── */}
            <div style={{ padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 12 }}>
              <button
                type="button"
                onClick={() => navigate('/assets')}
                className="btn-secondary"
              >
                Cancel
              </button>
              <button
                id="register-asset-btn"
                type="submit"
                disabled={isSubmitting}
                className="btn-primary"
                aria-busy={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Registering…
                  </>
                ) : (
                  <>
                    <Package className="h-4 w-4" />
                    Register Asset
                  </>
                )}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
